os: linux
dist: xenial
language: python

cache: pip

services:
  # to be able to display
  - xvfb

before_install:
  - sudo apt-get update

jobs:
  include:
    - python: 2.7
      env: TOXENV=py27-pyqt-build
    - python: 2.7
      env: TOXENV=py27-pyside-build

    - python: 3.6
      env: TOXENV=py36-pyqt5-build
    - python: 3.6
      env: TOXENV=py36-pyside2-build
    - python: 3.9
      env: TOXENV=py39-pyqt5-build
    - python: 3.9
      env: TOXENV=py39-pyside2-build

    - python: 3.9
      env: TOXENV=py39-lint
    - python: 3.9
      env: TOXENV=py39-safety
    - python: 3.9
      env: TOXENV=py39-metric
    - python: 3.9
      env: TOXENV=py39-develop

    - python: 3.9
      env: TOXENV=py39-pyqt5-doc

    - python: 3.9
      env: TOXENV=py39-release



install:
  # to make sure it has everything up to date
  - python -V
  - python -m ensurepip
  - python -m pip install -U pip
  - python -m pip install -U setuptools
  - python -m pip install -U wheel
  - python -m pip install -U virtualenv
  - python -m pip install -U tox

script:
  - tox
