name: Build - test - docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build - Python ${{ matrix.python-version }}, ${{ matrix.platform }}, 
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 2
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Build with tox
      run: tox
      env:
        PLATFORM: ${{ matrix.platform }}
        TASK: build
  test:
    needs: [build]
    name: Test ${{ matrix.tasks }}
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 2
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
        tasks: [lint, safety, metric, develop, doc, release]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Testing ${{ matrix.tasks }}
      run: tox
      env:
        PLATFORM: ${{ matrix.platform }}
        TASK: ${{ matrix.tasks }}
  docs:
    needs: [build, test]
    name: Create docs for GitHub Pages 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r req-doc.txt
        
    - name: Sphinx Build
      run: |
        cd docs
        sphinx-build -b html . _build

    - name: Upload to Github Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: docs/_build/
        target_branch: gh-pages
        jekyll: false
        committer: Wojciech Wentland <wojciech.wentland@int.pl>
        author: Wojciech Wentland <wojciech.wentland@int.pl>
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
